# Generated by Django 3.1.6 on 2021-05-30 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('door_dash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doordashstats',
            old_name='gasCost',
            new_name='gas_cost',
        ),
        migrations.RenameField(
            model_name='doordashstats',
            old_name='netPay',
            new_name='net_pay',
        ),
        migrations.RenameField(
            model_name='doordashstats',
            old_name='otherCosts',
            new_name='other_costs',
        ),
    ]
