# Generated by Django 3.1.6 on 2021-05-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_dash', '0002_auto_20210529_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doordashstats',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
