# Generated by Django 3.1.6 on 2021-05-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_dash', '0003_auto_20210529_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doordashstats',
            name='date',
            field=models.DateField(max_length=255),
        ),
    ]
