# Generated by Django 3.1.6 on 2021-05-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_dash', '0006_auto_20210530_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doordashstats',
            name='gas_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
