# Generated by Django 3.1.6 on 2021-05-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_dash', '0007_auto_20210530_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='doordashstats',
            name='weekday',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
