# Generated by Django 3.1.6 on 2021-05-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_dash', '0008_doordashstats_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doordashstats',
            name='weekday',
            field=models.CharField(choices=[('monday', 'MON'), ('tuesday', 'TUES'), ('wednesday', 'WED'), ('thursday', 'THURS'), ('friday', 'FRI'), ('saturday', 'SAT'), ('sunday', 'SUN')], default='monday', max_length=9),
        ),
    ]
