# Generated by Django 3.1.6 on 2021-05-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_dash', '0009_auto_20210530_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doordashstats',
            name='weekday',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUES', 'Tuesday'), ('WED', 'Wednesday'), ('THURS', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='monday', max_length=9),
        ),
    ]
